apiVersion: v1
kind: Service
metadata:
  name: techtrends-svc
  labels:
    app: techtrends-app
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: techtrends-app
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetport }}
