apiVersion: v1
kind: Service
metadata:
  name: techtrends-svc
  labels:
    app: techtrends-app
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: techtrends-app
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
